Own Review
AmaliaGM/OwnReview pull request #1
Opened 2022-06-06 21:34 UTC by AmaliaGM

I did a sushi product presentation. Included a nav bar at the page top with logo and a hamburguer button to the right, Introduced icons from a web page in order to connect menu links (hamburguer button) to this and create a responsive page, as I did with contact information also.
We added a product demonstration and prices chart.

2022-06-06 22:25 UTC, AmaliaGM reviewed
You did a great job.  Your commit messages could be more descriptive of your work. The icons could be aligned with the rest of the file (centered) 
Keep up the good work!

2022-06-06 22:34 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @AmaliaGM, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

Your comment was professional and polite ✔️

## Aspects to improve ♻️

- [ ] You should use inline comments so the author of the project can easily understand the context of your comment. [Check this link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md)
- [ ] Remember to add a minimum of 2 comments as it is a requirement for this project. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-07 11:46 UTC, AmaliaGM commented
@leonardodiasb Thanks for your review.

2022-06-07 12:00 UTC, AmaliaGM reviewed
Your page looks very nice and has some little details that would make it look better!
-Please take a look at the changes I´ve detailed for you.
-Have in mind also that commit messages are in order for someone else to know about your work at that period of time so it would be nice for you to give a more descriptive name to them.
Over all you´re doing a good job. Keep it up!
Happy codding =)

2022-06-07 12:00 UTC, AmaliaGM commented on index.html
> +  <div class="container">
You could align all the elements to the titles it would look nice

2022-06-07 12:00 UTC, AmaliaGM commented on README.md
> +👤 **Author1**
You could addapt your readme file to your proyect it woul make people know and appreciate your work better.

2022-06-07 12:11 UTC, KayLemba approved these changes
# Project Approved 🚀

Hi @AmaliaGM   🥇,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

## Highlights 
- You included an explanation, a "why", for each requested change 🎉 
-  You phrased the comments politely, as suggestions instead of orders 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- Kindly include emojis and gifs to make your code review more human-friendly 🙂 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-07 12:47 UTC, merged